lambda_function_name   = "uploaded_video"
s3_bucket_name         = "fonte-lambda-uploaded-video"
lambda_s3_key          = "lambda_uploaded_video.zip"
lambda_role_name       = "lambda_uploaded_video_exec_role"
s3_backend_bucket_name = "6soat-tfstate"
aws_region             = "sa-east-1"
